# Generated by Django 4.1.1 on 2022-09-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auctionlisting_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='image',
            field=models.CharField(blank=True, default='No image', max_length=10240, null=True),
        ),
    ]
